### ISSUE TITLE
Запуск стенда одной кнопкой

### ISSUE THREAD

**Issue by inthedark122** [Ksaltotun/MOK#5]
Необходимо написать скрипт `start` для запускать приложения в режиме разработке.
Под запуском подразумеваем:

1. Запуск мок сервера
1. Запуск сервера (пример https://www.npmjs.com/package/serve)

UI часть должна быть доступна по http://localhost:3000

### Полезная фича:

Добавить watch команду для перезагрузки сервера после изменений в коде

### Полезная литература:

1. ифно о скриптах https://frontender.info/task_automation_with_npm_run/ https://docs.npmjs.com/misc/scripts

**Comment by Ksaltotun** [comment]
Это готово
