### ISSUE TITLE
Проверка на стайл гайды

### ISSUE THREAD

**Issue by inthedark122** [Ksaltotun/MOK#6]
1. Добавить eslint конфиг в проект
1. Добавить скрипт `lint: eslint public/javascript --ext js` который будет проверять код на ошибки
1. Добавить https://github.com/typicode/husky https://github.com/okonet/lint-staged
1. Пример использования https://medium.com/gits-apps-insight/utilizing-git-hook-by-using-eslint-husky-and-lint-staged-18b6f6f60f1e

**Comment by Ksaltotun** [comment]
добавил скрипт, добавил с помощью хаски пре-коммит скрипт (с еслинт-стаже)
